# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import longcat_chat_pb2 as longcat__chat__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in longcat_chat_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PythonAiChatServiceStub(object):
    """Python AI后端聊天服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamThinkChat = channel.unary_stream(
                '/pythonai.PythonAiChatService/StreamThinkChat',
                request_serializer=longcat__chat__pb2.ThinkChatRequest.SerializeToString,
                response_deserializer=longcat__chat__pb2.ThinkChatResponse.FromString,
                _registered_method=True)
        self.GenerateQuestions = channel.unary_unary(
                '/pythonai.PythonAiChatService/GenerateQuestions',
                request_serializer=longcat__chat__pb2.GenerateQuestionsRequest.SerializeToString,
                response_deserializer=longcat__chat__pb2.GenerateQuestionsResponse.FromString,
                _registered_method=True)
        self.EvaluateAnswer = channel.unary_unary(
                '/pythonai.PythonAiChatService/EvaluateAnswer',
                request_serializer=longcat__chat__pb2.EvaluateAnswerRequest.SerializeToString,
                response_deserializer=longcat__chat__pb2.EvaluateAnswerResponse.FromString,
                _registered_method=True)
        self.GenerateSummary = channel.unary_unary(
                '/pythonai.PythonAiChatService/GenerateSummary',
                request_serializer=longcat__chat__pb2.GenerateSummaryRequest.SerializeToString,
                response_deserializer=longcat__chat__pb2.GenerateSummaryResponse.FromString,
                _registered_method=True)
        self.RunInterviewAgent = channel.unary_unary(
                '/pythonai.PythonAiChatService/RunInterviewAgent',
                request_serializer=longcat__chat__pb2.InterviewAgentRequest.SerializeToString,
                response_deserializer=longcat__chat__pb2.InterviewAgentResponse.FromString,
                _registered_method=True)


class PythonAiChatServiceServicer(object):
    """Python AI后端聊天服务
    """

    def StreamThinkChat(self, request, context):
        """保留：流式思考对话
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateQuestions(self, request, context):
        """新增：生成面试问题（非流式）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateAnswer(self, request, context):
        """新增：评价用户回答（非流式）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateSummary(self, request, context):
        """新增：生成面试总结（非流式）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunInterviewAgent(self, request, context):
        """Stateful interview orchestration. The Java service persists state and
        sends one decision request for each interview turn.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PythonAiChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamThinkChat': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamThinkChat,
                    request_deserializer=longcat__chat__pb2.ThinkChatRequest.FromString,
                    response_serializer=longcat__chat__pb2.ThinkChatResponse.SerializeToString,
            ),
            'GenerateQuestions': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateQuestions,
                    request_deserializer=longcat__chat__pb2.GenerateQuestionsRequest.FromString,
                    response_serializer=longcat__chat__pb2.GenerateQuestionsResponse.SerializeToString,
            ),
            'EvaluateAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateAnswer,
                    request_deserializer=longcat__chat__pb2.EvaluateAnswerRequest.FromString,
                    response_serializer=longcat__chat__pb2.EvaluateAnswerResponse.SerializeToString,
            ),
            'GenerateSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateSummary,
                    request_deserializer=longcat__chat__pb2.GenerateSummaryRequest.FromString,
                    response_serializer=longcat__chat__pb2.GenerateSummaryResponse.SerializeToString,
            ),
            'RunInterviewAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RunInterviewAgent,
                    request_deserializer=longcat__chat__pb2.InterviewAgentRequest.FromString,
                    response_serializer=longcat__chat__pb2.InterviewAgentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pythonai.PythonAiChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pythonai.PythonAiChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PythonAiChatService(object):
    """Python AI后端聊天服务
    """

    @staticmethod
    def StreamThinkChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pythonai.PythonAiChatService/StreamThinkChat',
            longcat__chat__pb2.ThinkChatRequest.SerializeToString,
            longcat__chat__pb2.ThinkChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateQuestions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pythonai.PythonAiChatService/GenerateQuestions',
            longcat__chat__pb2.GenerateQuestionsRequest.SerializeToString,
            longcat__chat__pb2.GenerateQuestionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluateAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pythonai.PythonAiChatService/EvaluateAnswer',
            longcat__chat__pb2.EvaluateAnswerRequest.SerializeToString,
            longcat__chat__pb2.EvaluateAnswerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pythonai.PythonAiChatService/GenerateSummary',
            longcat__chat__pb2.GenerateSummaryRequest.SerializeToString,
            longcat__chat__pb2.GenerateSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunInterviewAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pythonai.PythonAiChatService/RunInterviewAgent',
            longcat__chat__pb2.InterviewAgentRequest.SerializeToString,
            longcat__chat__pb2.InterviewAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
