'use client';
import { useEffect, useRef, useState } from 'react';
import type { Candle, Trade } from '@/lib/simulator';
export const money = (n: number, digits = 2) => new Intl.NumberFormat('zh-CN', { minimumFractionDigits: digits, maximumFractionDigits: digits }).format(n);
export const compact = (n: number) => Math.abs(n) >= 10000 ? `${money(n / 10000, 1)}万` : money(n, Math.abs(n) >= 1000 ? 0 : 2);
function useWidth() { const ref = useRef<HTMLDivElement>(null), [width, setWidth] = useState(650); useEffect(() => { if (!ref.current) return; const observer = new ResizeObserver(entries => setWidth(Math.max(220, Math.floor(entries[0].contentRect.width)))); observer.observe(ref.current); return () => observer.disconnect(); }, []); return { ref, width }; }
export function LineGraph({ series, labels, unit = '元', height = 250, percent = false }: { series: { name: string; values: number[]; color: string; dashed?: boolean }[]; labels?: string[]; unit?: string; height?: number; percent?: boolean }) {
  const { ref, width } = useWidth(), [hover, setHover] = useState<number | null>(null), [hidden, setHidden] = useState<string[]>([]);
  const visible = series.filter(s => !hidden.includes(s.name)), all = visible.flatMap(s => s.values), count = Math.max(1, ...visible.map(s => s.values.length));
  const left = 50, right = 16, top = 25, bottom = 34, plotW = width - left - right, plotH = height - top - bottom;
  let min = Math.min(...all, 0), max = Math.max(...all, 1);
  if (!percent && min >= 0) min = Math.min(...all) * .94;
  const padding = (max - min) * .08 || 1; min -= padding; max += padding;
  const x = (i: number) => left + (count === 1 ? .5 : i / (count - 1)) * plotW, y = (n: number) => top + (max - n) / (max - min) * plotH;
  const point = hover === null ? count - 1 : Math.max(0, Math.min(count - 1, hover)), index = Math.min(count - 1, Math.round(point));
  const interpolate = (values: number[]) => { if (values.length === 1) return values[0]; const p = point / (count - 1) * (values.length - 1), a = Math.floor(p), b = Math.min(values.length - 1, a + 1); return values[a] + (values[b] - values[a]) * (p - a); };
  return <div className="line-graph" ref={ref}><div className="chart-legend">{series.map(s => <button key={s.name} className={hidden.includes(s.name) ? 'muted' : ''} aria-pressed={!hidden.includes(s.name)} onClick={() => setHidden(old => old.includes(s.name) ? old.filter(n => n !== s.name) : old.length < series.length - 1 ? [...old, s.name] : old)}><i style={{ background: s.color }} />{s.name}</button>)}<span className="chart-unit">{unit}</span></div><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${series.map(s => `${s.name}：从${money(s.values[0])}到${money(s.values.at(-1) || 0)}`).join('；')}。单位${unit}`} onPointerMove={event => { const rect = event.currentTarget.getBoundingClientRect(); setHover(Math.max(0, Math.min(count - 1, ((event.clientX - rect.left) * width / rect.width - left) / plotW * (count - 1)))); }} onPointerLeave={() => setHover(null)}>
    <defs><linearGradient id={`graph-gradient-${series[0]?.name.replace(/[^a-z\d]/gi, '') || 'main'}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={series[0]?.color} stopOpacity=".12"/><stop offset="1" stopColor={series[0]?.color} stopOpacity="0"/></linearGradient></defs>
    {[0, 1, 2, 3].map(i => { const value = min + (max - min) * i / 3; return <g key={i}><line x1={left} y1={y(value)} x2={width - right} y2={y(value)} stroke="var(--chart-grid)" strokeDasharray="3 5"/><text x={left - 9} y={y(value) + 4} textAnchor="end" className="axis-text">{percent ? `${money(value, 1)}%` : compact(value)}</text></g>; })}
    {visible.map((s, si) => { const path = s.values.map((v, i) => `${i ? 'L' : 'M'} ${x(i / Math.max(1, s.values.length - 1) * (count - 1))} ${y(v)}`).join(' '); return <g key={s.name}>{s.values.length === 1 && <circle cx={x(0)} cy={y(s.values[0])} r="4" fill={s.color}/>} {si === 0 && <path d={`${path} L ${x(count - 1)} ${height - bottom} L ${x(0)} ${height - bottom} Z`} fill={s.color} opacity=".05"/>}<path d={path} fill="none" stroke={s.color} strokeWidth="2.4" strokeDasharray={s.dashed ? '5 5' : undefined} strokeLinejoin="round" strokeLinecap="round"/></g>; })}
    {[...new Set([0, Math.floor((count - 1) / 2), count - 1])].map((i, j) => <text key={j} x={x(i)} y={height - 11} textAnchor={j === 0 ? 'start' : j === 2 ? 'end' : 'middle'} className="axis-text">{labels?.[i] || `${i}`}</text>)}
    {hover !== null && <g><line x1={x(point)} x2={x(point)} y1={top} y2={height - bottom} stroke="#84928a" strokeDasharray="3 4"/>{visible.map(s => <circle key={s.name} cx={x(point)} cy={y(interpolate(s.values))} r="4" fill={s.color} stroke="var(--surface)" strokeWidth="2"/>)}</g>}
  </svg><div className="chart-readout" aria-live="off"><span>{labels?.[index] || `观察点 ${index}`}</span>{visible.map(s => <strong key={s.name} style={{ color: s.color }}>{s.name} {money(interpolate(s.values), percent ? 2 : 0)}{percent ? '%' : ''}</strong>)}</div><input className="chart-scrubber" type="range" min="0" max={count - 1} step="1" value={index} onChange={event => setHover(Number(event.target.value))} aria-label="选择图表观察点"/></div>;
}

export function PriceChart({ candles, mode = 'candle', trades = [], volumeUnit = '股', priceUnit = '元' }: { candles: Candle[]; mode?: 'candle' | 'line'; trades?: Trade[]; volumeUnit?: string; priceUnit?: string }) {
  const { ref, width } = useWidth(), [index, setIndex] = useState<number | null>(null);
  const height = 330, left = 51, right = 16, top = 18, priceBottom = 234, volumeTop = 257, bottom = 305;
  const min = Math.min(...candles.map(c => c.low)) * .98, max = Math.max(...candles.map(c => c.high)) * 1.02, plotW = width - left - right;
  const x = (i: number) => left + (i + .5) / candles.length * plotW, y = (v: number) => top + (max - v) / (max - min || 1) * (priceBottom - top), volumeMax = Math.max(1, ...candles.map(c => c.volume)), barW = Math.max(1.5, Math.min(9, plotW / candles.length * .65));
  const selectedIndex = index === null ? null : Math.min(index, candles.length - 1);
  const selected = candles[selectedIndex ?? candles.length - 1];
  if (!selected) return <p className="muted">等待价格序列</p>;
  return <div ref={ref} className="price-chart"><div className="ohlc-readout"><span>{selected.date}</span>{[['开', selected.open], ['高', selected.high], ['低', selected.low], ['收', selected.close]].map(([label, value]) => <span key={label}> {label} <strong>{money(Number(value))}</strong></span>)}<span>量 <strong>{compact(selected.volume)}</strong></span></div><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${candles.length}个交易日的${mode === 'candle' ? 'K线' : '收盘价格'}与成交量；当前观察收盘${selected.close}${priceUnit}。红色表示收盘高于开盘，绿色表示收盘低于开盘。`} onPointerMove={event => { const rect = event.currentTarget.getBoundingClientRect(); setIndex(Math.max(0, Math.min(candles.length - 1, Math.floor(((event.clientX - rect.left) * width / rect.width - left) / plotW * candles.length)))); }} onPointerLeave={() => setIndex(null)}>
    {[0, 1, 2, 3].map(i => { const v = min + (max - min) * i / 3; return <g key={i}><line x1={left} x2={width - right} y1={y(v)} y2={y(v)} stroke="var(--chart-grid)" strokeDasharray="3 5"/><text x={left - 10} y={y(v) + 4} textAnchor="end" className="axis-text">{money(v, 1)}</text></g>; })}
    {mode === 'line' ? <path d={candles.map((c, i) => `${i ? 'L' : 'M'} ${x(i)} ${y(c.close)}`).join(' ')} fill="none" stroke="#427db4" strokeWidth="2.4" strokeLinejoin="round"/> : candles.map((c, i) => <g key={c.day} stroke={c.close >= c.open ? '#d96d68' : '#4c9281'}><line x1={x(i)} x2={x(i)} y1={y(c.high)} y2={y(c.low)} strokeWidth="1.1"/><rect x={x(i) - barW / 2} y={Math.min(y(c.open), y(c.close))} width={barW} height={Math.max(1.3, Math.abs(y(c.open) - y(c.close)))} fill={c.close >= c.open ? '#d96d68' : '#4c9281'} stroke="none"/></g>)}
    <line x1={left} x2={width - right} y1={priceBottom + 14} y2={priceBottom + 14} stroke="var(--chart-grid)"/><text x={left} y={volumeTop - 2} className="axis-text">成交量 · {volumeUnit}</text>
    {candles.map((c, i) => <rect key={c.day} x={x(i) - barW / 2} y={bottom - c.volume / volumeMax * 40} width={barW} height={c.volume / volumeMax * 40} fill={c.close >= c.open ? '#d96d68' : '#4c9281'} opacity=".45"/>)}
    {trades.map(t => { const i = candles.findIndex(c => c.day === t.day); return i < 0 ? null : <g key={t.id}><circle cx={x(i)} cy={y(t.price)} r="8" fill={t.side === 'buy' ? '#d96d68' : '#488377'} stroke="var(--surface)" strokeWidth="2"/><text x={x(i)} y={y(t.price) + 3} textAnchor="middle" fill="white" fontSize="8">{t.side === 'buy' ? '买' : '卖'}</text></g>; })}
    {selectedIndex !== null && <g><line x1={x(selectedIndex)} x2={x(selectedIndex)} y1={top} y2={bottom} stroke="#89958e" strokeDasharray="3 5"/><circle cx={x(selectedIndex!)} cy={y(selected.close)} r="4" fill="#488377" stroke="var(--surface)" strokeWidth="2"/></g>}
    {[0, Math.floor((candles.length - 1) / 2), candles.length - 1].map((i, j) => <text key={j} x={x(i)} y={height - 8} textAnchor={j === 0 ? 'start' : j === 2 ? 'end' : 'middle'} className="axis-text">{candles[i].date.slice(5).replace('-', '/')}</text>)}
  </svg><div className="chart-readout"><span>红：收 ≥ 开　绿：收 &lt; 开</span><span>指向或拖动查看每一日</span></div><input className="chart-scrubber" type="range" min="0" max={candles.length - 1} value={selectedIndex ?? candles.length - 1} onChange={event => setIndex(Number(event.target.value))} aria-label="选择K线交易日"/></div>;
}
export function Ring({ value, label, detail, dark = false }: { value: number; label: string; detail?: string; dark?: boolean }) {
  const ratio = Math.max(0, Math.min(100, value));
  return <div className={`ring ${dark ? 'dark-ring' : ''}`}><svg viewBox="0 0 240 240" role="img" aria-label={`${label} ${money(value, 1)}%`}><circle cx="120" cy="120" r="93" fill="none" stroke={dark ? '#ffffff12' : '#e4eef7'} strokeWidth="19"/><circle cx="120" cy="120" r="93" fill="none" stroke={dark ? '#99cef6' : '#75a6d3'} strokeWidth="19" strokeDasharray={`${ratio / 100 * 584.34} 584.34`} transform="rotate(-90 120 120)" strokeLinecap="round"/><text x="120" y="121" textAnchor="middle" className="ring-value">{money(value, value < 10 ? 1 : 0)}<tspan fontSize="17">%</tspan></text><text x="120" y="150" textAnchor="middle" className="ring-label">{label}</text></svg>{detail && <p>{detail}</p>}</div>;
}
export function HorizontalBars({ items, unit = '元' }: { items: { label: string; value: number; color?: string }[]; unit?: string }) {
  const max = Math.max(1, ...items.map(i => Math.abs(i.value)));
  return <div className="horizontal-bars" role="img" aria-label={items.map(i => `${i.label}${money(i.value)}${unit}`).join('；')}>{items.map((item, i) => <div className="bar-row" key={i}><div><span>{item.label}</span><strong>{money(item.value, Math.abs(item.value) >= 100 ? 0 : 2)}<small>{unit}</small></strong></div><div className="bar-rail"><span style={{ width: `${Math.abs(item.value) / max * 100}%`, background: item.color || (item.value < 0 ? '#cf8882' : '#76a3cf') }}/></div></div>)}</div>;
}
