'use client';
import { ArrowRight } from 'lucide-react';
import { DailyAverageExample } from './daily-average';

export function ConceptFigure({ id }: { id: string }) {
  if (id === 'candle') return <div className="concept-figure candle-figure" role="img" aria-label="昨天收盘10元，今天开盘9.1元、最高10.2元、最低9元、收盘9.5元。阳线但相对昨收下跌5%。"><div className="candle-drawing"><i className="candle-wick"/><i className="candle-body"/><span className="candle-high">最高 10.20</span><span className="candle-close">收盘 9.50</span><span className="candle-open">开盘 9.10</span><span className="candle-low">最低 9.00</span></div><div><b>阳线 ≠ 比昨天上涨</b><p>实体比较“收盘与开盘”；涨跌幅比较“今天收盘与昨天收盘”。</p><strong className="down">9.50 ÷ 10.00 − 1 = −5%</strong></div></div>;
  if (id === 'orderbook' || id === 'beginner-first-order') return <div className="concept-figure book-figure"><div className="teaching-book"><div><span>卖三</span><b>10.03</b><span>500 股</span></div><div><span>卖二</span><b>10.02</b><span>200 股</span></div><div className="best-level"><span>卖一</span><b>10.01</b><span>100 股</span></div><div className="book-spread">价差 0.01 元</div><div className="best-level"><span>买一</span><b>10.00</b><span>300 股</span></div><div><span>买二</span><b>9.99</b><span>400 股</span></div></div><div><b>限价 10.02 元，买 500 股</b><p>先买卖一的 100 股，再买卖二的 200 股。剩下 200 股等待，不会用 10.03 元越过你的限价。</p><strong>已成交均价 ≈ 10.0167 元</strong><small>示例未计税费；时间优先用于同价订单排队。</small></div></div>;
  if (id === 'beginner-accounts') return <div className="concept-figure flow-figure"><div className="cash-stations"><div><span>本人银行卡</span><b>银行存款</b><small>通过正规银证转账划转资金</small></div><ArrowRight/><div><span>证券资金账户</span><b>可用 / 可取</b><small>用于结算；两种余额未必相同</small></div><ArrowRight/><div><span>证券账户</span><b>股份与基金份额</b><small>记录持有什么资产</small></div></div><p>证券买卖不会直接在银行卡余额里变成一行股票。三方存管、证券账户和券商资金账户各有职责，要分别看持仓、可用资金和可取资金。</p></div>;
  if (id === 'beginner-markets') return <div className="concept-figure market-figure"><div className="market-comparison">{[['沪深主板',10,'核对普通权限与产品类别'],['创业板',20,'新增权限有单独适当性要求'],['科创板',20,'权限与申报数量都要单独核验'],['北交所',30,'普通准入与科创板权限例外要区分']].map(([name,limit,note])=><div key={name}><b>{name}</b><strong>通常 ±{limit}%</strong><span className="market-range"><i style={{width:`${Number(limit)/30*100}%`}}/></span><small>{note}</small></div>)}</div><p>这是 2026-10-02 核验的股票常规单日范围比较。新股上市初期、特定退市整理日等有例外；它不代表单日最大损失承诺，也不能保证跌停时卖得出。资产与经验条件、申报规则在下方逐项解释，ETF 不直接套此表。</p><DailyAverageExample/></div>;
  if (id === 'beginner-opening') return <div className="concept-figure flow-figure"><div className="opening-stations">{['核对资格与正规机构','准备本人身份与银行卡','实名认证与风险测评','阅读协议与风险揭示','审核账户与三方存管','核对权限、费用和入金'].map((step,i)=><div key={step}><span>{String(i+1).padStart(2,'0')}</span><b>{step}</b><small>{['不要通过陌生人提供的开户链接','证件、手机号和银行卡资料按券商核对','按真实财务状况与经验回答','逐项阅读，不为追求权限改写答案','资金划入本人正规存管渠道','先练模拟操作，再自行决定是否交易'][i]}</small></div>)}</div><p>这里演示开户流程，不收集证件或办理开户；年龄例外、受理方式、审核时间和可开权限按现行规则与券商正式渠道核验。</p></div>;
  if (id === 'review' || id === 'beginner-protection') return <div className="concept-figure flow-figure"><div className="cash-stations"><div><span>先留证据</span><b>事实是什么？</b><small>保存原文、费用协议与操作记录</small></div><ArrowRight/><div><span>再检查推理</span><b>哪里是假设？</b><small>结果相反时，过程还能成立吗</small></div><ArrowRight/><div><span>最后做行动</span><b>核对与复盘</b><small>从正规客服和官方入口求证</small></div></div><p>保证收益、催促转账或把钱转到个人账户的要求，不应当作为投资证据。一次盈利也不能替代来源核验和风险判断。</p></div>;
  if (id === 'equity') return <div className="concept-figure equity-figure"><div className="share-tile" aria-label="100个方格里一个高亮，表示1%持股">{Array.from({length:100},(_,i)=><i key={i} className={i===0?'owned':''}/>)}</div><div><b>10,000 股中的 100 股</b><strong>持股比例 = 1%</strong><p>对应公司利润的份额，不是自动到账的现金。证券账户记录你持有的股份，资金账户记录交易资金。</p></div></div>;
  if (id === 'valuation') return <div className="concept-figure equation-figure"><div><span>过去</span><strong>EPS 2.00 × PE 15</strong><b>价格 30.00 元</b></div><ArrowRight/><div><span>假设未来</span><strong>EPS 2.40 × PE 12</strong><b>价格 28.80 元</b></div><p>利润增长 20%，估值倍数下降 20%，两者相乘后股价仍跌 4%。PE 是市场定价口径，不是收益承诺。</p></div>;
  if (id === 'dividend') return <div className="concept-figure equation-figure"><div><span>分红前</span><strong>100 股 × 10.00</strong><b>股票价值 1,000 元</b></div><ArrowRight/><div><span>简化除息后</span><strong>100 股 × 9.50 + 50</strong><b>股票 950 + 现金 50</b></div><p>不计税费、其他市场变化和到账时差的教学例子：现金分红让价值换了一种形式。除息参考价不是成交价保证。</p></div>;
  if (id === 'compound' || id === 'drawdown') return <div className="concept-figure path-figure"><svg viewBox="0 0 540 160" role="img" aria-label="净值从100到120，再到84，最后110。总收益10%，最大回撤30%。"><path d="M40 90 L190 30 L350 138 L500 60" fill="none" stroke="var(--accent, #347cc0)" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round"/>{[[40,90,'100'],[190,30,'120'],[350,138,'84'],[500,60,'110']].map(([x,y,label],i)=><g key={i}><circle cx={x} cy={y} r="6" fill="var(--accent, #347cc0)"/><text x={x} y={Number(y)-12} textAnchor="middle">{label}</text></g>)}</svg><div><b>终点盈利，不抹去途中亏损</b><p>120 → 84：回撤 30%。84 → 120：需要上涨 42.86%。收益率按路径连乘，涨跌不能直接相抵。</p></div></div>;
  if (id === 'cashflow' || id === 'statements') return <div className="concept-figure flow-figure"><div className="cash-stations"><div><span>收入</span><b>1,000 万</b><small>卖出了多少</small></div><ArrowRight/><div><span>利润</span><b>500 万</b><small>收入 − 确认的费用</small></div><ArrowRight/><div><span>经营现金流</span><b>200 万</b><small>收款 700 − 付款 500</small></div></div><p>收入、利润和现金是三个不同问题。再买设备 100 万属于投资现金流；借款 400 万属于筹资现金流，不能当成赚了 400 万。</p></div>;
  if (id === 'costs') return <div className="concept-figure cost-figure"><div className="cost-stack" aria-label="总费用5.51元中，佣金约90.74%，印花税约9.07%，过户费约0.18%">{[['佣金','5.00',90.74],['卖出印花税','0.50',9.07],['过户费','0.01',0.18]].map(([name,amount,share])=><div key={name}><span>{name} <b>{amount} 元</b></span><i><i style={{width:`${share}%`}}/></i></div>)}</div><div><b>1,000 元的小额卖出</b><p>假设佣金最低 5 元、印花税万分之五、过户费十万分之一：合计 5.51 元。还要考虑买入费用与价差，涨一点不一定赚钱。</p><strong>实际佣金率 0.5% ≠ 名义万三</strong></div></div>;
  if (id === 'position' || id === 'beginner-money') return <div className="concept-figure position-figure"><div className="allocation-bar"><span style={{width:'30%'}}>股票 3 万</span><span style={{width:'70%'}}>现金 7 万</span></div><div><b>股票跌 30%，账户跌多少？</b><p>股票变成 2.1 万，现金仍为 7 万。总资产 9.1 万，账户下跌 9%；股票新仓位约 23.08%。</p><strong>仓位决定冲击传导的大小</strong></div></div>;
  if (id === 'diversification' || id === 'etf') return <div className="concept-figure basket-figure"><div className="basket-grid">{['消费','科技','制造','金融','能源','医疗'].map((v,i)=><span key={v} style={{background:`hsl(211 64% ${82+i*2}%)`}}>{v}</span>)}</div><div><b>数量多，不一定风险分散</b><p>若六家公司都依赖同一原料、同一客户或同一利率环境，一次冲击仍可能同时受损。ETF 也要看行业权重、前十大集中度、价差和费用。</p><strong>观察风险来源，比数股票更有用</strong></div></div>;
  if (id === 'news') return <div className="concept-figure equation-figure"><div><span>市场原先预期</span><strong>利润增长 30%</strong><b>已包含在价格中的期待</b></div><ArrowRight/><div><span>实际公布</span><strong>利润增长 20%</strong><b>增长为正，仍低于预期</b></div><p>消息对价格的影响还取决于预期、持续性、估值与风险。标题“增长”本身不足以推导“必涨”。</p></div>;
  return null;
}
