'use client';
import { useState } from 'react';
import { ArrowRight, ArrowUpRight, BookOpen, Check, Clock3, MessageCircle } from 'lucide-react';
import { CHAPTERS } from '@/lib/course';
import { COURSE_STAGES, type Lesson } from '@/lib/data';

export type LearningMapProps = { lessons: Lesson[]; stages: string[]; completed: string[]; next: Lesson; quizCount: number; onOpen: (id: string) => void; onAsk: (question: string) => void };
export function LearningMap({ lessons, completed, next, onOpen, onAsk }: LearningMapProps) {
  const [selected, setSelected] = useState<string | null>(null);
  return <div className="course-map">
    <header className="course-map-heading"><span className="reading-kicker">从零开始 · A股学习地图</span><h1>先把股票这件事<br/><em>弄明白。</em></h1><p>不用先开户，也不需要金融基础。<br/>从一家小店开始，一步步学到能独立看懂一次交易。</p><div className="map-heading-note"><BookOpen size={16}/>{lessons.length}课 · 四段旅程 · 随时可以停下来问</div><div className="map-art" aria-hidden="true"><span>一家公司</span><div>{Array.from({ length: 25 }, (_, i) => <i key={i} className={i < 5 ? 'owned' : ''}/>)}</div><p>一小部分，也能看清全貌。</p></div></header>
    <div className="map-start-row"><section className="map-continue"><div><span className="reading-kicker">{completed.length ? '接着往下学' : '从这里出发'}</span><h2>{next.title}</h2><p>{next.coreQuestion}</p><span className="map-time"><Clock3 size={14}/>约{next.minutes}分钟 · {CHAPTERS.find(c => c.id === next.id)?.format}</span></div><button className="button primary" onClick={() => onOpen(next.id)}>{next.id === lessons[0].id && !completed.length ? '读第一课' : '继续阅读'}<ArrowRight size={18}/></button></section><section className="map-helper"><MessageCircle size={24}/><h2>不知道从哪学？</h2><p>说说你现在卡在哪里，助手会带你找到具体的一课。</p><button onClick={() => onAsk('我是零基础，想先理解股票，不急着开户。请给我一个循序渐进的学习顺序。')}>帮我安排学习 <ArrowUpRight size={16}/></button></section></div>
    <section className="map-journey"><div className="map-journey-heading"><div><span className="reading-kicker">每走一段，多解决一个问题</span><h2>你的学习路线</h2></div><span>{completed.length} / {lessons.length} 课已读</span></div><div className="map-stage-tabs" role="group" aria-label="筛选学习阶段"><button aria-pressed={!selected} onClick={() => setSelected(null)}>完整路线</button>{COURSE_STAGES.map((stage, i) => <button key={stage.title} aria-pressed={selected === stage.title} onClick={() => setSelected(stage.title)}>{String(i + 1).padStart(2, '0')} · {stage.title}</button>)}</div>
    {COURSE_STAGES.filter(s => !selected || s.title === selected).map(stage => <section key={stage.title} className="map-stage"><div className="map-stage-intro"><span className="map-stage-number">{String(COURSE_STAGES.indexOf(stage) + 1).padStart(2, '0')}</span><div><h3>{stage.title}</h3><p>{stage.description}</p></div></div><div className="map-lesson-grid">{lessons.filter(l => l.stage === stage.title).map(lesson => { const chapter = CHAPTERS.find(c => c.id === lesson.id)!; return <button className={`map-lesson ${lesson.id === next.id ? 'next' : ''}`} onClick={() => onOpen(lesson.id)} key={lesson.id}><span className="map-lesson-number">{String(lessons.indexOf(lesson) + 1).padStart(2, '0')}</span><div><h4>{lesson.title}</h4><p>{lesson.coreQuestion}</p><span>{chapter.format}<i/>约{lesson.minutes}分钟</span></div>{completed.includes(lesson.id) ? <Check size={20} aria-label="已阅读"/> : <ArrowUpRight size={19}/>}</button>; })}</div></section>)}
    </section><div className="map-end-note"><span>学完并不要求你马上投资。</span><p>能看懂、会核对、知道自己还不懂什么，就是这条路线的目的。</p></div>
  </div>;
}
