'use client';
import { useState } from 'react';
import { ArrowRight, Check } from 'lucide-react';

export type StudyQuestion={question:string;options:string[];answerIndex:number;explanation:string;optionExplanations?:string[];difficulty?:string};
export function LessonQuiz({ id, questions, busy, available, onSave, previous }: { id:string;questions:StudyQuestion[];busy:boolean;available:boolean;onSave:(answers:number[])=>Promise<boolean>;previous?:{correct:number;answers:number[]} }) {
  const [answers,setAnswers]=useState<number[]>(questions.map(()=>-1)),[submitted,setSubmitted]=useState(false),[saving,setSaving]=useState(false);
  const answered=answers.filter(a=>a>=0).length,score=answers.filter((a,i)=>a===questions[i].answerIndex).length;
  return <section className="quiz-section study-quiz"><div className="section-heading"><div><span className="eyebrow">CHECK YOUR UNDERSTANDING</span><h2>能解释为什么，才算真的理解。</h2></div><span className="tag">{questions.length} 道情境题</span></div>{previous&&<p className="quiet">上次测验答对 {previous.correct} / {previous.answers.length} 题{previous.answers.length!==questions.length?'；本课题库已扩充，建议重新挑战。':'。'}</p>}<div className="quiz-progress"><span>{submitted?`本次答对 ${score} / ${questions.length}`:`已作答 ${answered} / ${questions.length}`}</span><div><i style={{width:`${answered/questions.length*100}%`}}/></div></div><div className="quiz-grid">{questions.map((q,i)=><fieldset key={i} className="quiz-card" disabled={busy||saving}><legend><span>{String(i+1).padStart(2,'0')}</span>{q.question}</legend>{q.difficulty&&<span className="quiz-difficulty">{q.difficulty}</span>}{q.options.map((option,a)=><label className={`quiz-option ${submitted&&a===q.answerIndex?'correct':submitted&&answers[i]===a?'incorrect':''}`} key={a}><input type="radio" name={`${id}-question-${i}`} checked={answers[i]===a} onChange={()=>{setAnswers(old=>old.map((v,j)=>j===i?a:v));setSubmitted(false);}}/><span><b>{String.fromCharCode(65+a)}.</b>{option}</span>{submitted&&a===q.answerIndex&&<Check size={16}/>}</label>)}{submitted&&<div className="quiz-feedback"><p><b>{answers[i]===q.answerIndex?'判断正确':'再想一步'}</b> · {q.explanation}</p>{q.optionExplanations&&<details><summary>逐项看看：其他选项为什么不成立？</summary><ol type="A">{q.optionExplanations.map((ex,j)=><li key={j}>{ex}</li>)}</ol></details>}</div>}</fieldset>)}</div><div className="quiz-actions"><button className="button primary" disabled={busy||saving||!available||answered!==questions.length} onClick={async()=>{const submittedAnswers=[...answers];setSaving(true);try{if(await onSave(submittedAnswers)){setAnswers(submittedAnswers);setSubmitted(true);}}finally{setSaving(false);}}}>提交并查看详细解析 <ArrowRight size={16}/></button>{submitted?<button className="text-button" disabled={busy||saving} onClick={()=>{setAnswers(questions.map(()=>-1));setSubmitted(false);}}>重新挑战</button>:<span>完成全部题目后查看答案。先判断，再比较证据。</span>}</div><div className="quiz-status" role="status" aria-live="polite">{submitted?`已保存：答对 ${score} / ${questions.length}。${score===questions.length?'试着把概念讲给另一个新手。':'展开错题解析，查清漏掉的条件后再练一次。'}`:''}</div></section>;
}
